language: java

jdk:
  - openjdk14

sudo: false

env:
  global:
    - CODECOV_TOKEN="28cffc0c-1d9b-44f5-9e4c-aaa0753df40d"

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонний сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    recipients:
      - egorsarantsev4565@mail.ru
    on_success: never # default: change
    on_failure: always # default: always